# Generated by Django 2.0.3 on 2018-04-30 23:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
                ('satisfactory_level', models.IntegerField()),
                ('comments', models.TextField()),
                ('name', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('phone_number', models.TextField(blank=True)),
            ],
            options={
                'permissions': (('view_feedback', 'View feedback'),),
            },
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.FileField(blank=True, upload_to='C:/Users/Marshall Smith/Desktop/Django/mysite/RockHawk/media')),
                ('name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('hotspot_radius', models.IntegerField()),
                ('visitor_count', models.IntegerField()),
                ('hotspot_info', models.TextField()),
                ('location_type', models.IntegerField(choices=[(0, 'Facility'), (1, 'Activity'), (2, 'Hotspot')])),
            ],
        ),
        migrations.CreateModel(
            name='TrailData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('trail_info', models.TextField()),
                ('trail_length_in_miles', models.FloatField()),
                ('trail_latitudes', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None)),
                ('trail_longitudes', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None)),
                ('trail_type', models.IntegerField(choices=[(0, 'Foot'), (1, 'Biking'), (2, 'Multi-Use')])),
            ],
        ),
    ]
