# Generated by Django 2.0.2 on 2018-04-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
                ('satisfactory_level', models.IntegerField()),
                ('comments', models.TextField()),
            ],
            options={
                'permissions': (('view_feedback', 'View feedback'),),
            },
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('hotspotRadius', models.IntegerField()),
                ('visitorCount', models.IntegerField()),
                ('trailInfo', models.TextField()),
                ('locationType', models.IntegerField(choices=[(0, 'Facility'), (1, 'Activity'), (2, 'Hotspot')])),
            ],
        ),
    ]
