# Generated by Django 2.0.2 on 2018-03-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RockHawk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'permissions': (('view_feedback', 'View feedback'),)},
        ),
    ]
