# Generated by Django 2.0.2 on 2018-03-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RockHawk', '0002_auto_20180328_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('hotspotRadius', models.IntegerField()),
                ('visitorCount', models.IntegerField()),
                ('trailInfo', models.TextField()),
            ],
        ),
    ]
