# Generated by Django 2.0.2 on 2018-03-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RockHawk', '0003_locationdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationBasedData',
        ),
    ]
