# Generated by Django 2.0.2 on 2018-03-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gpa',
            new_name='age',
        ),
    ]
